//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class SCEContextDataContext : Microsoft.SharePoint.Linq.DataContext
{

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCEIB")]
    public Microsoft.SharePoint.Linq.EntityList<SCEIBListFieldsContentType> SCEIBList
    {
        get
        {
            return this.GetList<SCEIBListFieldsContentType>("SCEIB");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCEIGCSE")]
    public Microsoft.SharePoint.Linq.EntityList<SCEIGCSEListFieldsContentType> SCEIGCSEList
    {
        get
        {
            return this.GetList<SCEIGCSEListFieldsContentType>("SCEIGCSE");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCERequests")]
    public Microsoft.SharePoint.Linq.EntityList<SCERequestsListFieldsContentType> SCERequestsList
    {
        get
        {
            return this.GetList<SCERequestsListFieldsContentType>("SCERequests");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SchoolSystem")]
    public Microsoft.SharePoint.Linq.EntityList<SchoolSystemLookupsCT> SchoolSystemList
    {
        get
        {
            return this.GetList<SchoolSystemLookupsCT>("SchoolSystem");
        }
    }

    ///// <summary>
    ///// My List Instance
    ///// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "EquivalencyPurpose")]
    public Microsoft.SharePoint.Linq.EntityList<EquivalencyPurposeLookupsCT> EquivalencyPurposeList
    {
        get
        {
            return this.GetList<EquivalencyPurposeLookupsCT>("EquivalencyPurpose");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "CertificateType")]
    public Microsoft.SharePoint.Linq.EntityList<CertificateTypeListFieldsContentType> CertificateTypeList
    {
        get
        {
            return this.GetList<CertificateTypeListFieldsContentType>("CertificateType");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "CertificateType")]
    public Microsoft.SharePoint.Linq.EntityList<CertificateTypeLookupsCT> CertificateTypeCT
    {
        get
        {
            return this.GetList<CertificateTypeLookupsCT>("CertificateType");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Applicants")]
    public Microsoft.SharePoint.Linq.EntityList<ApplicantsListFieldsContentType> ApplicantsList
    {
        get
        {
            return this.GetList<ApplicantsListFieldsContentType>("Applicants");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "ScholasticLevel")]
    public Microsoft.SharePoint.Linq.EntityList<ScholasticLevelLookupsCT> ScholasticLevelList
    {
        get
        {
            return this.GetList<ScholasticLevelLookupsCT>("ScholasticLevel");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SchoolType")]
    public Microsoft.SharePoint.Linq.EntityList<SchoolTypeLookupsCT> SchoolTypeList
    {
        get
        {
            return this.GetList<SchoolTypeLookupsCT>("SchoolType");
        }
    }


    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Nationality")]
    public Microsoft.SharePoint.Linq.EntityList<NationalityListFieldsContentType> NationalityList
    {
        get
        {
            var ss = this.GetList<NationalityListFieldsContentType>("Nationality");
            return this.GetList<NationalityListFieldsContentType>("Nationality");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCEClarificationsRequests")]
    public Microsoft.SharePoint.Linq.EntityList<SCEClarificationsRequestsListFieldsContentType> SCEClarificationsRequestsList
    {
        get
        {
            return this.GetList<SCEClarificationsRequestsListFieldsContentType>("SCEClarificationsRequests");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "ClarificationReasons")]
    public Microsoft.SharePoint.Linq.EntityList<ClarificationReasonsLookupsCT> ClarificationReasonsList
    {
        get
        {
            return this.GetList<ClarificationReasonsLookupsCT>("ClarificationReasons");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "AttachmentsLookup")]
    public Microsoft.SharePoint.Linq.EntityList<AttachmentsLookupListFieldsContentType> AttachmentsLookupList
    {
        get
        {
            return this.GetList<AttachmentsLookupListFieldsContentType>("AttachmentsLookup");
        }
    }

    /// <summary>
    /// My List Instance
    /// </summary>
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCENavigationLinks")]
    public Microsoft.SharePoint.Linq.EntityList<SCENavigationLinksListFieldsContentType> SCENavigationLinksList
    {
        get
        {
            return this.GetList<SCENavigationLinksListFieldsContentType>("SCENavigationLinks");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "CountryOfStudy")]
    public Microsoft.SharePoint.Linq.EntityList<CountryOfStudyListFieldsContentType> CountryOfStudyList
    {
        get
        {
            return this.GetList<CountryOfStudyListFieldsContentType>("CountryOfStudy");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "NationalityCategory")]
    public Microsoft.SharePoint.Linq.EntityList<NationalityCategoryListFieldsContentType> NationalityCategoryList
    {
        get
        {
            return this.GetList<NationalityCategoryListFieldsContentType>("NationalityCategory");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "RequestTypes")]
    public Microsoft.SharePoint.Linq.EntityList<RequestTypesListFieldsContentType> RequestTypesList
    {
        get
        {
            return this.GetList<RequestTypesListFieldsContentType>("RequestTypes");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCERequestsAssignments")]
    public Microsoft.SharePoint.Linq.EntityList<SCERequestsAssignmentsListFieldsContentType> SCERequestsAssignmentsList
    {
        get
        {
            return this.GetList<SCERequestsAssignmentsListFieldsContentType>("SCERequestsAssignments");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "FileName")]
    public Microsoft.SharePoint.Linq.EntityList<FileNameListFieldsContentType> FileNameList
    {
        get
        {
            return this.GetList<FileNameListFieldsContentType>("FileName");
        }
    }

    public Microsoft.SharePoint.Linq.EntityList<LookupsCT> RejectionReasonsList
    {
        get
        {
            return this.GetList<LookupsCT>("RejectionReasons");
        }
    }

    public Microsoft.SharePoint.Linq.EntityList<LookupsCT> ReturnReasonsList
    {
        get
        {
            return this.GetList<LookupsCT>("ReturnReasons");
        }
    }


  
    public Microsoft.SharePoint.Linq.EntityList<LookupsCT> RecommendationsList
    {
        get
        {
            return this.GetList<LookupsCT>("Recommendations");
        }
    }

    public Microsoft.SharePoint.Linq.EntityList<SCEPMDecisionListFieldsContentType> SCEPMDecisionList
    {
        get
        {
            return this.GetList<SCEPMDecisionListFieldsContentType>("SCEPMDecision");
        }
    }

    public Microsoft.SharePoint.Linq.EntityList<SCEHMDecisionListFieldsContentType> SCEHMDecisionList
    {
        get
        {
            return this.GetList<SCEHMDecisionListFieldsContentType>("SCEHMDecision");
        }
    }

    public Microsoft.SharePoint.Linq.EntityList<SCENotificationsListFieldsContentType> SCENotificationsList
    {
        get
        {
            return this.GetList<SCENotificationsListFieldsContentType>("SCENotifications");
        }
    }
    public Microsoft.SharePoint.Linq.EntityList<SCERequestHistoryListFieldsContentType> SCERequestHistoryList
    {
        get
        {
            return this.GetList<SCERequestHistoryListFieldsContentType>("SCERequestHistory");
        }
    }

    public Microsoft.SharePoint.Linq.EntityList<SCEUnauthorizedReasonListFieldsContentType> SCEUnauthorizedReasonList
    {
        get
        {
            return this.GetList<SCEUnauthorizedReasonListFieldsContentType>("SCEUnauthorizedReason");
        }
    }



    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCESearchStatusRecommendation")]
    public Microsoft.SharePoint.Linq.EntityList<SCESearchStatusRecommendationListFieldsContentType> SCESearchStatusRecommendationList
    {
        get
        {
            return this.GetList<SCESearchStatusRecommendationListFieldsContentType>("SCESearchStatusRecommendation");
        }
    } 

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCEEmployees")]
    public Microsoft.SharePoint.Linq.EntityList<SCEEmployeesListFieldsContentType> SCEEmployeesList
    {
        get
        {
            return this.GetList<SCEEmployeesListFieldsContentType>("SCEEmployees");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "StatementAgency")]
    public Microsoft.SharePoint.Linq.EntityList<StatementAgencyListFieldsContentType> StatementAgencyList
    {
        get
        {
            return this.GetList<StatementAgencyListFieldsContentType>("StatementAgency");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCEStatementsRequests")]
    public Microsoft.SharePoint.Linq.EntityList<SCEStatementsRequestsListFieldsContentType> SCEStatementsRequestsList
    {
        get
        {
            return this.GetList<SCEStatementsRequestsListFieldsContentType>("SCEStatementsRequests");
        }
    }

    public Microsoft.SharePoint.Linq.EntityList<SCEHMReturnRequestsListFieldsContentType> SCEHMReturnRequestsList
    {
        get
        {
            return this.GetList<SCEHMReturnRequestsListFieldsContentType>("SCEHMReturnRequests");
        }
    }


    public Microsoft.SharePoint.Linq.EntityList<SCEPMReturnRequestsListFieldsContentType> SCEPMReturnRequestsList
    {
        get
        {
            return this.GetList<SCEPMReturnRequestsListFieldsContentType>("SCEPMReturnRequests");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCEBooksRequests")]
    public Microsoft.SharePoint.Linq.EntityList<SCEBooksRequestsListFieldsContentType> SCEBooksRequestsList
    {
        get
        {
            return this.GetList<SCEBooksRequestsListFieldsContentType>("SCEBooksRequests");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "ExCommAgency")]
    public Microsoft.SharePoint.Linq.EntityList<ExCommAgencyListFieldsContentType> ExCommAgencyList
    {
        get
        {
            return this.GetList<ExCommAgencyListFieldsContentType>("ExCommAgency");
        }
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "IGDegree")]
    public Microsoft.SharePoint.Linq.EntityList<IGDegreeListFieldsContentType> IGDegreeList
    {
        get
        {
            return this.GetList<IGDegreeListFieldsContentType>("IGDegree");
        }
    }
    [Microsoft.SharePoint.Linq.ListAttribute(Name = "SCERequestsAttachments")]
    public Microsoft.SharePoint.Linq.EntityList<SCERequestsAttachmentsListFieldsContentType> SCERequestsAttachmentsList
    {
        get
        {
            return this.GetList<SCERequestsAttachmentsListFieldsContentType>("SCERequestsAttachments");
        }
    }
}