//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOEHE.PSPES.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOE_RELATIONSHIP
    {
        public int MOE_RELATIONSHIP_TYPE_ID { get; set; }
        public string MOE_RELATIONSHIP_NAME_ENG { get; set; }
        public string MOE_RELATIONSHIP_NAME_ARA { get; set; }
    }
}
