//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOEHE.PSPES.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOE_BIO_DATA
    {
        public int ID { get; set; }
        public Nullable<decimal> NATIONAL_ID { get; set; }
        public string MOE_ENGLISH_NAME { get; set; }
        public string MOE_ARABIC_NAME { get; set; }
        public Nullable<System.DateTime> MOE_DOB { get; set; }
        public string MOE_GENDER { get; set; }
        public string MOE_COUNTRY_ENGLISH_NAME { get; set; }
        public string MOE_COUNTRY_ARABIC_NAME { get; set; }
        public Nullable<int> MOE_COUNTRY_CODE { get; set; }
        public string MOE_STATUS { get; set; }
        public Nullable<System.DateTime> MOE_STATUS_DATE { get; set; }
        public Nullable<System.DateTime> MOE_LAST_UPDATED_DATE { get; set; }
        public Nullable<System.DateTime> MOE_TRANSACTION_DTTM { get; set; }
        public string MOE_USERID { get; set; }
    }
}
