//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOEHE.PSPES.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOE_GUARDIAN_DATA
    {
        public int ID { get; set; }
        public Nullable<decimal> NATIONAL_ID { get; set; }
        public string MOE_APPL_NBR { get; set; }
        public Nullable<decimal> MOE_RELATED_QID { get; set; }
        public string MOE_RELATIONSHIP_TYPE_ID { get; set; }
        public Nullable<bool> MOE_ISGUARDIAN { get; set; }
        public string MOE_MARITAL_STATUS_ID { get; set; }
        public string MOE_HOME_CONTACT_NBR { get; set; }
        public string MOE_WORK_CONTACT_NBR { get; set; }
        public string MOE_MOBILE_CONTACT_NBR { get; set; }
        public string MOE_FAX_CONTACT_NBR { get; set; }
        public string MOE_EMAIL { get; set; }
        public string MOE_EMPLOYER_TYPE_ID { get; set; }
        public string MOE_EMPLOYER { get; set; }
        public Nullable<System.DateTime> MOE_TRANSACTION_DTTM { get; set; }
        public string MOE_USERID { get; set; }
        public string IsActive { get; set; }
        public string MOE_GUARDIAN_NAME_ENG { get; set; }
        public string MOE_GUARDIAN_NAME_ARA { get; set; }
    }
}
