//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOEHE.PSPES.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOE_ADDED_CAPACITY
    {
        public int ID { get; set; }
        public Nullable<int> MOE_SCHOOL_YEAR { get; set; }
        public string MOE_SCHOOL_CODE { get; set; }
        public Nullable<int> MOE_ADDED_CAPACITY1 { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> DTTM { get; set; }
    }
}
