//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOEHE.PSPES.WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrivateScoolsPreEnrollmentEntities222 : DbContext
    {
        public PrivateScoolsPreEnrollmentEntities222()
            : base("name=PrivateScoolsPreEnrollmentEntities222")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddedGrade> AddedGrades { get; set; }
        public virtual DbSet<EnrollementControlling> EnrollementControllings { get; set; }
        public virtual DbSet<Enrollment_Exception_Attachment> Enrollment_Exception_Attachment { get; set; }
        public virtual DbSet<InterviewResult> InterviewResults { get; set; }
        public virtual DbSet<MessageTemplate> MessageTemplates { get; set; }
        public virtual DbSet<MOE_ADDED_CAPACITY> MOE_ADDED_CAPACITY { get; set; }
        public virtual DbSet<MOE_AGE_VALIDATE_Temp> MOE_AGE_VALIDATE_Temp { get; set; }
        public virtual DbSet<MOE_APPL_ACAD_INFO> MOE_APPL_ACAD_INFO { get; set; }
        public virtual DbSet<MOE_APPL_SUPPORT_DOCS> MOE_APPL_SUPPORT_DOCS { get; set; }
        public virtual DbSet<MOE_Application_DATA> MOE_Application_DATA { get; set; }
        public virtual DbSet<MOE_BIO_DATA> MOE_BIO_DATA { get; set; }
        public virtual DbSet<MOE_CURRICULUM_LOOKUP> MOE_CURRICULUM_LOOKUP { get; set; }
        public virtual DbSet<MOE_DOUBLE_CURRICULUM_MAPPING> MOE_DOUBLE_CURRICULUM_MAPPING { get; set; }
        public virtual DbSet<MOE_ENROLLMENT_EXCEPTION> MOE_ENROLLMENT_EXCEPTION { get; set; }
        public virtual DbSet<MOE_ENROLLMENT_EXCEPTION_AUDIT> MOE_ENROLLMENT_EXCEPTION_AUDIT { get; set; }
        public virtual DbSet<MOE_Enrollment_Exception_Types> MOE_Enrollment_Exception_Types { get; set; }
        public virtual DbSet<MOE_GUARDIAN_DATA> MOE_GUARDIAN_DATA { get; set; }
        public virtual DbSet<MOE_HEALTH_DATA> MOE_HEALTH_DATA { get; set; }
        public virtual DbSet<MOE_MARITAL_STATUS> MOE_MARITAL_STATUS { get; set; }
        public virtual DbSet<MOE_MARITIALSTATUS_LOOKUP> MOE_MARITIALSTATUS_LOOKUP { get; set; }
        public virtual DbSet<MOE_RELATIONSHIP> MOE_RELATIONSHIP { get; set; }
        public virtual DbSet<MOE_RELATIONSHIP_LOOKUP> MOE_RELATIONSHIP_LOOKUP { get; set; }
        public virtual DbSet<MOE_SCHOOL> MOE_SCHOOL { get; set; }
        public virtual DbSet<MOE_SEAT_CAPACITY> MOE_SEAT_CAPACITY { get; set; }
        public virtual DbSet<MOE_TERM> MOE_TERM { get; set; }
        public virtual DbSet<MOE_WITHDRAWAL_REASON> MOE_WITHDRAWAL_REASON { get; set; }
        public virtual DbSet<MOI_Country_Map> MOI_Country_Map { get; set; }
        public virtual DbSet<NotificationAction> NotificationActions { get; set; }
        public virtual DbSet<SeatReservationFee> SeatReservationFees { get; set; }
        public virtual DbSet<SMSHistory> SMSHistories { get; set; }
        public virtual DbSet<SupportingDocumentSetup> SupportingDocumentSetups { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<TransactionsLog> TransactionsLogs { get; set; }
        public virtual DbSet<BuildingCapacity> BuildingCapacities { get; set; }
        public virtual DbSet<MOE_AGE_VALIDATE> MOE_AGE_VALIDATE { get; set; }
        public virtual DbSet<MOE_EMPLOYER_DATA> MOE_EMPLOYER_DATA { get; set; }
        public virtual DbSet<MOE_EMPLOYER_TYPE> MOE_EMPLOYER_TYPE { get; set; }
        public virtual DbSet<MOE_GRADE> MOE_GRADE { get; set; }
        public virtual DbSet<Testing> Testings { get; set; }
        public virtual DbSet<MOE_PREENROLLMENT_REPORT_VIEW> MOE_PREENROLLMENT_REPORT_VIEW { get; set; }
        public virtual DbSet<V_Schools_Grades_Ages> V_Schools_Grades_Ages { get; set; }
        public virtual DbSet<MOE_WITHDRAWAL_DATA> MOE_WITHDRAWAL_DATA { get; set; }
    }
}
