//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOEHE.PSPES.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsLog
    {
        public int ID { get; set; }
        public Nullable<int> ActionCode { get; set; }
        public string TableName { get; set; }
        public string UserID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
