"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Department Manager Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/DepartmentManager.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Deputy Minister Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/AssistantUndersecretary.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Employees Review Final Decision Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/PrimaryAndSecondaryEmployee.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Employees Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/PrimaryEmployee.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Legal Affairs Employee Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/LegalAffairs.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Program Manager Receive Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/ProgramEmployee.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Program Manager Review Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/ProgramManager.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Reception Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/Receptionist.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Requester Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/Applicant.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Technical Committee Task From Dept Manager" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/TechnicalCommitte.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE CE Technical Committee Task From Deputy Minister" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.UCE/TechnicalCommitteUnderSec.aspx" -formType All -updateChildren Yes
