"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Department Manager Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/DepartmentManager.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Deputy Minister Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/AssistantUndersecretary.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Employees Review Final Decision Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/PrimaryAndSecondaryEmployee.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Employees Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/PrimaryEmployee.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Legal Affairs Employee Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/LegalAffairs.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Program Manager Receive Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/ProgramEmployee.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Program Manager Review Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/ProgramManager.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Reception Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/Receptionist.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Requester Task" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/Applicant.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Technical Committee Task From Dept Manager" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/TechnicalCommitte.aspx" -formType All -updateChildren Yes
"C:\Program Files\Nintex\Nintex Workflow 2010\nwadmin.exe" -o SetTaskForm -siteUrl "http://moehe-dev-05" -contentType "MOEHE PA Technical Committee Task From Deputy Minister" -taskformUrl "/_layouts/15/ITWORX.MOEHEWF.PA/TechnicalCommitteUnderSec.aspx" -formType All -updateChildren Yes
